### ISSUE TITLE
OAuth 2 login fail for gateway generated with "server only"

### ISSUE THREAD

**Issue by littlepine** [jhipster/generator-jhipster-svelte#1482]
Steps to reproduce: 

1. Using keycloak as oauth 2 server
2. use sever-only flag
3. Start the app server on 8080
4. Generate the svelte client
5. login
6. input admin / admin
7. Server return 404

Root cause:
the vite config set `changeOrigin: true` which make the keycloak set the `return_uri` to `localhost:8080`. It should be `localhost:5173`.

Solution:

Change the generated vite.config.ts to following:

```
import { sveltekit } from '@sveltejs/kit/vite';
import type { UserConfig } from 'vite';

const config: UserConfig = {
	server: {
		proxy: {
			'/api': {
				target: 'http://localhost:8080',
				changeOrigin: false,
			},
			'/management': {
				target: 'http://localhost:8080',
				changeOrigin: false,
			},
			'/oauth2': {
				target: 'http://localhost:8080',
				changeOrigin: false,
			},
			'/login': {
				target: 'http://localhost:8080',
				changeOrigin: false,
			},
			'/auth': {
				target: 'http://localhost:8080',
				changeOrigin: false,
			},
		},
	},
	plugins: [sveltekit()],
	ssr: {
		noExternal: ['jhipster-svelte-library'],
	},
};

export default config;
```

It should fix the problem.

**Comment by vishal423** [comment]
Generating separate frontend/backend applications and then using them together is an advanced configuration that may require manual tuning. I will take a look at the above recommendation. Thanks
