### ISSUE TITLE
Enable lighthouse GitHub Actions job

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster-svelte#1612]
The Lighthouse job was temporarily disabled in [#1611](https://github.com/jhipster/generator-jhipster-svelte/pull/1611) as it was failing due to recent `puppeteer` or `lhci/cli` updates. This ticket is to investigate the cause and enable the job.

**Comment by zhyd1997** [comment]
Hi team, I can take this ticket if nobody worked on it! :eyes:

**Comment by vishal423** [comment]
@zhyd1997, I haven't started on this issue, so, please go ahead.

**Comment by zhyd1997** [comment]
@vishal423 great thanks!
