### ISSUE TITLE
Support nodejs LTS v18

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster-svelte#1841]

**Comment by vishal423** [comment]
Latest stable release of JHipster `v7.9.4` still doesn't correctly exports the inner sub-generators or utils being used in this blueprint making it incompatible to be used in NodeJS `v18.x` environment.

``` "./generators/": "./generators/",```

should be 
``` "./generators/*": "./generators/*/index.js",```

**Comment by vishal423** [comment]
@mshima , Could you please take a look on the JHipster side? If not possible for the 7.x branch, then, I think we should target for the upcoming v8 release.

**Comment by mshima** [comment]
It’s already fixed at v8.

There is not a good alternative for path exports.
Should be something like:
```
"generators/*.js": "generators/*.js",
"generators/*": "generators/*/index.js",
"generators/*/index.js": "generators/*/index.js",
"generators/*/files.js": "generators/*/files.js",
```
Probably we need to re-export needles and others.
Usually changing exports alone requires a major version bump. 

I wonder if worth the testing/releasing efforts since v8 is close.

**Comment by vishal423** [comment]
If it requires more work in the v7.x codebase, then, I am fine to wait for the v8 release
