### ISSUE TITLE
Support JHipster v8 release

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster-svelte#1862]

**Comment by vishal423** [comment]
@pascalgrimaud, can we add some bounty on this ticket?

**Comment by pascalgrimaud** [comment]
@vishal423 : done

**Comment by mshima** [comment]
@vishal423 do you want some help migrating to v8?

**Comment by vishal423** [comment]
@mshima, It would be really helpful if you can take up this ticket.

**Comment by vishal423** [comment]
@mshima, are you planning to continue on this ticket?

**Comment by mshima** [comment]
@vishal423 I cannot take the lead on this.
The differences on the implementation makes difficult for me.
This blueprint ci is heavy on docker,  it creates an image and uses it everywhere.

Others blueprints supports `generate-sample` and is easy to reproduce ci samples.
```
jhipster-(entity-audit/micronaut/quarkus/nhipster/ionic) generate-samples # select the sample
npm ci:frontend:test
npm ci:backend:test
```

You can use the v8 branch to help you migrate and let me know if you need some help.

**Comment by vishal423** [comment]
closing as most of the upgrade issues have been resolved

**Comment by vishal423** [comment]
@mshima, please do claim half of the bounty as your initial PR helped on few tricky upgrade parts.

cc: @pascalgrimaud

**Comment by pascalgrimaud** [comment]
I'm increasing the bounty so it will be better to share, @vishal423 and @mshima

**Comment by vishal423** [comment]
Thanks @pascalgrimaud

**Comment by vishal423** [comment]
@pascalgrimaud  bounty claimed https://opencollective.com/generator-jhipster/expenses/199462

**Comment by mshima** [comment]
> @mshima, please do claim half of the bounty as your initial PR helped on few tricky upgrade parts.
> 
> cc: @pascalgrimaud

Sorry for the late response I’ve missed it.

Thanks @vishal423 glad it helped, let me know if you need and assistance to migrate to any other version.

Thanks @pascalgrimaud

**Comment by pascalgrimaud** [comment]
@vishal423 : approved

@mshima : you're welcome, it's deserved :-)

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/203357.

**Comment by pascalgrimaud** [comment]
@mshima : approved

**Comment by mshima** [comment]
@pascalgrimaud thanks.
