### ISSUE TITLE
Release next blueprint version

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster-svelte#2255]
- [x] Upgrade `JHipster` dependencies 
- [x] Bump third party dependencies
- [x] Migrate EsLint dependency
- [x] Update change log, examples
- [x] Update jhipster svelte library dependencies, eslint, other confs
- [x] Prepare release and polish configurations

**Comment by vishal423** [comment]
@pascalgrimaud , @mraible , Can we add some bounty for next release publish?

**Comment by mraible** [comment]
@vishal423 What amount do you think is appropriate?

**Comment by mraible** [comment]
Done!
