### ISSUE TITLE
unable to find generator-jhipster-svelte in npm registry

### ISSUE THREAD

**Issue by Rajpratik71** [jhipster/generator-jhipster-svelte#34]
[INFO] npm ERR! code E404
[INFO] npm ERR! 404 Not Found - GET https://registry.npmjs.org/generator-jhipster-svelte - Not found
[INFO] npm ERR! 404
[INFO] npm ERR! 404  'generator-jhipster-svelte@0.0.0' is not in the npm registry.
[INFO] npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
[INFO] npm ERR! 404 It was specified as a dependency of 'test'

**Comment by vishal423** [comment]
It's still in early development and yet to release a version. Meantime, you can follow https://github.com/jhipster/generator-jhipster-svelte#hammer_and_wrench-development
