### ISSUE TITLE
Rename the default branch from master to main

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster-svelte#44]
Related to https://github.com/jhipster/generator-jhipster/issues/11935

Do you think is it possible @vishal423 ?
Do you want me to do it ?

**Comment by vishal423** [comment]
@pascalgrimaud, If you have time, then, feel free to do this change. Otherwise, I will try over coming weekend. As this is a new repository, we should delete `master` after this change and keep only `main` to avoid any confusion.

**Comment by pascalgrimaud** [comment]
@vishal423 : ok, I'll do it this morning (in few hours)

**Comment by pascalgrimaud** [comment]
just done !
