### ISSUE TITLE
Integrate entity generator - Create, Edit page

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster-svelte#471]
- [x] Generate create page supporting all JDL data types along with e2e tests
- [x] Support edit entity flow

**Comment by vishal423** [comment]
Related #58

**Comment by vishal423** [comment]
@pascalgrimaud  bounty claimed @ https://opencollective.com/generator-jhipster/expenses/61022

**Comment by pascalgrimaud** [comment]
@vishal423 : approved
