### ISSUE TITLE
Integrate JHipster OIDC authentication type

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster-svelte#50]
Current generator code supports session authentication type. This issue is a placeholder to track integration with OIDC authentication type

**Comment by mraible** [comment]
I'd be willing to sponsor this feature if I'm given the ability to add a bug bounty.

**Comment by vishal423** [comment]
@pascalgrimaud can you help over here?

**Comment by pascalgrimaud** [comment]
@mraible : you should be admin of this repo, like @vishal423

**Comment by mraible** [comment]
@pascalgrimaud Thanks! It looks like this repo is missing bug bounty labels.

**Comment by vishal423** [comment]
@mraible , I have added respective bug bounty labels. Let me know if you still see any discrepancies.

**Comment by mraible** [comment]
@vishal423 Looks good! I added a bounty. Let me know if you need more $$ or bug bounties on other issues.

**Comment by vishal423** [comment]
Thanks @mraible . You may want to check if  #46 #172 #464 #470, #471 qualify the bounty criteria 😄

**Comment by vishal423** [comment]
Following @deepu105 email, can we add some bounty on #46 #172 #464 #470 #471 ?
cc: @pascalgrimaud @jdubois

**Comment by deepu105** [comment]
@vishal423 done, let me know if the amount is enough

**Comment by vishal423** [comment]
thanks @deepu105
