### ISSUE TITLE
Integrate a CRUD type entity editor

### ISSUE THREAD

**Issue by windbender** [jhipster/generator-jhipster-svelte#58]
straight jhipster hands you a CURD based editor for each of your entities.   jhipster-svelte should do the same.

**Comment by vishal423** [comment]
We will of course add support for entity CRUD, however, there are other priority items to get the current release out of the beta. Any contributions are welcome.

**Comment by vishal423** [comment]
Closing as most of CRUD support is in place and will be available in next release
