### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster-svelte#877]
Related to https://github.com/jhipster/generator-jhipster-svelte/releases/tag/v0.7.0

Adding a bounty for all the work done here @vishal423

**Comment by vishal423** [comment]
Thanks @pascalgrimaud

**Comment by vishal423** [comment]
@pascalgrimaud  bounty claimed @ https://opencollective.com/generator-jhipster/expenses/61023

**Comment by pascalgrimaud** [comment]
@vishal423 : approved :)
